from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from app.core.mongodb import users_col

security = HTTPBearer()

async def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    
    try:
        # DEVELOPMENT FALLBACK: Allow mock tokens generated by the auth service
        if token.startswith("mock_jwt_token_for_"):
            email = token.replace("mock_jwt_token_for_", "")
            # Verify user exists in MongoDB
            user = await users_col.find_one({"email": email})
            if not user:
                # If they just logged in, they should exist. If not, return minimal info
                return {"email": email, "id": "mock-user-id", "full_name": email.split('@')[0].capitalize()}
            return user

        # In a real production setup, you'd decode a real JWT here
        # For now, we maintain the mock logic but integrated with MongoDB users
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid session token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except Exception as e:
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Authentication failed: {str(e)}",
            headers={"WWW-Authenticate": "Bearer"},
        )
