"use client";

import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';

interface Flashcard {
    id: string;
    front: string;
    back: string;
    mastery_level: number;
}

interface FlashcardViewProps {
    cards: Flashcard[];
    onClose: () => void;
}

export default function FlashcardView({ cards, onClose }: FlashcardViewProps) {
    const [currentIndex, setCurrentIndex] = useState(0);
    const [isFlipped, setIsFlipped] = useState(false);
    const [direction, setDirection] = useState(0);

    const handleNext = () => {
        if (currentIndex < cards.length - 1) {
            setDirection(1);
            setCurrentIndex(prev => prev + 1);
            setIsFlipped(false);
        }
    };

    const handlePrev = () => {
        if (currentIndex > 0) {
            setDirection(-1);
            setCurrentIndex(prev => prev - 1);
            setIsFlipped(false);
        }
    };

    const currentCard = cards[currentIndex];

    const downloadCards = async () => {
        const html2pdf = (await import('html2pdf.js')).default;
        let cHtml = '';
        for (let i = 0; i < cards.length; i++) {
            const c = cards[i];
            const front = c.front.replace(/</g, '&lt;');
            const back = c.back.replace(/</g, '&lt;');
            cHtml += `<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:28px;padding:20px;border-radius:20px;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06)"><div style="padding:28px 24px;border-radius:24px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;min-height:200px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1)"><span style="font-size:10px;text-transform:uppercase;letter-spacing:0.12em;font-weight:900;color:#818cf8;opacity:0.6;margin-bottom:16px">Question / Term</span><span style="font-size:16px;font-weight:600;color:#fff;line-height:1.5;word-break:break-word">${front}</span><span style="font-size:9px;color:rgba(255,255,255,0.2);font-weight:700;text-transform:uppercase;letter-spacing:0.05em;margin-top:auto;padding-top:16px">Card ${i + 1} of ${cards.length}</span></div><div style="padding:28px 24px;border-radius:24px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;min-height:200px;background:rgba(99,102,241,0.15);border:1px solid rgba(99,102,241,0.25)"><span style="font-size:10px;text-transform:uppercase;letter-spacing:0.12em;font-weight:900;color:#22d3ee;opacity:0.7;margin-bottom:16px">Answer / Definition</span><span style="font-size:16px;font-weight:600;color:#fff;line-height:1.5;word-break:break-word">${back}</span></div></div>`;
        }

        const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
*{margin:0;padding:0;box-sizing:border-box}
.header{text-align:center;padding:0 0 32px;border-bottom:1px solid rgba(255,255,255,0.06)}
.header h1{font-size:28px;font-weight:800;background:linear-gradient(135deg,#818cf8,#60a5fa,#22d3ee);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;letter-spacing:-0.02em}
.header p{color:rgba(255,255,255,0.35);font-size:13px;margin-top:8px;font-weight:500}
@media(max-width:640px){.card-pair{grid-template-columns:1fr}}
.footer{text-align:center;padding:40px 0;color:rgba(255,255,255,0.15);font-size:12px}
</style></head><body>
<div class="header"><h1>Flashcards</h1><p>${cards.length} cards</p></div>
${cHtml}
<div class="footer">Generated by StudyFlow AI</div>
</body></html>`;

        const div = document.createElement('div');
        div.style.cssText = 'width:800px;padding:0 24px;background:#020617;color:#f8fafc;font-family:system-ui,-apple-system,sans-serif;position:fixed;left:50%;top:0;transform:translateX(-50%);z-index:-1;pointer-events:none';
        let clean = html.replace(/<!DOCTYPE[^>]*>/i, '').replace(/<\/?html[^>]*>/gi, '').replace(/<\/?head[^>]*>/gi, '').replace(/<\/?body[^>]*>/gi, '').replace(/<meta[^>]*>/gi, '').replace(/<title[^>]*>.*?<\/title>/gi, '');
        div.innerHTML = clean;
        document.body.appendChild(div);
        try {
            await new Promise(r => requestAnimationFrame(r));
            await html2pdf().set({
                margin: 10,
                filename: `flashcards_${new Date().toISOString().slice(0, 10)}.pdf`,
                image: { type: 'jpeg', quality: 0.95 },
                html2canvas: { scale: 2, useCORS: true, backgroundColor: '#020617', logging: true, width: div.scrollWidth, height: div.scrollHeight, scrollY: 0, windowHeight: div.scrollHeight },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            }).from(div).save();
        } catch (e) {
            console.error('PDF generation error:', e);
        } finally {
            document.body.removeChild(div);
        }
    };

    if (typeof window === 'undefined') return null;

    return createPortal(
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md"
        >
            <div className="w-full max-w-lg flex flex-col items-center">
                <div className="w-full flex items-center justify-between mb-6 md:mb-8 px-2 md:px-4">
                    <button
                        onClick={onClose}
                        className="text-white/40 hover:text-white transition-colors text-sm"
                    >
                        ✕ Close
                    </button>
                    <div className="flex items-center gap-3">
                        <button onClick={downloadCards} className="text-white/40 hover:text-white transition-colors text-sm" title="Download Flashcards">📥</button>
                        <div className="px-3 md:px-4 py-1.5 rounded-full bg-white/5 border border-white/10 text-xs font-bold text-white/60">
                            {currentIndex + 1}/{cards.length}
                        </div>
                    </div>
                </div>

                {/* Card Container */}
                <div className="relative w-full aspect-[4/3] max-h-[60vh] perspective-1000">
                    <AnimatePresence mode="wait" custom={direction}>
                        <motion.div
                            key={currentIndex}
                            custom={direction}
                            initial={{ x: direction * 50, opacity: 0, scale: 0.9 }}
                            animate={{ x: 0, opacity: 1, scale: 1 }}
                            exit={{ x: -direction * 50, opacity: 0, scale: 0.9 }}
                            transition={{ type: "spring", damping: 20, stiffness: 100 }}
                            className="w-full h-full cursor-pointer group"
                            onClick={() => setIsFlipped(!isFlipped)}
                        >
                            <motion.div
                                className="w-full h-full relative preserve-3d transition-transform duration-700"
                                animate={{ rotateY: isFlipped ? 180 : 0 }}
                                transition={{ type: "spring", damping: 15, stiffness: 100 }}
                            >
                                {/* Front */}
                                <div className="absolute inset-0 backface-hidden flex flex-center">
                                    <div className="w-full h-full glass-dark border border-white/10 rounded-[24px] md:rounded-[32px] p-6 md:p-12 flex flex-col items-center justify-center text-center shadow-2xl group-hover:border-primary/30 transition-all duration-300">
                                        <span className="text-[10px] md:text-xs uppercase tracking-widest font-black text-primary mb-4 md:mb-6 opacity-60">Question / Term</span>
                                        <h3 className="text-lg md:text-2xl font-bold text-white leading-relaxed">
                                            {currentCard.front}
                                        </h3>
                                        <div className="mt-auto text-white/20 text-[10px] font-bold uppercase tracking-tighter">Click to Flip</div>
                                    </div>
                                </div>

                                {/* Back */}
                                <div className="absolute inset-0 backface-hidden rotate-y-180 flex flex-center">
                                    <div className="w-full h-full bg-primary/20 border border-primary/30 rounded-[24px] md:rounded-[32px] p-6 md:p-12 flex flex-col items-center justify-center text-center shadow-2xl backdrop-blur-3xl overflow-y-auto">
                                        <span className="text-[10px] md:text-xs uppercase tracking-widest font-black text-emerald-400 mb-4 md:mb-6 opacity-60">Answer / Definition</span>
                                        <p className="text-base md:text-xl text-white/90 leading-relaxed font-medium">
                                            {currentCard.back}
                                        </p>
                                        <div className="mt-6 md:mt-8 text-white/20 text-[10px] font-bold uppercase tracking-tighter">Click to Flip Back</div>
                                    </div>
                                </div>
                            </motion.div>
                        </motion.div>
                    </AnimatePresence>
                </div>

                {/* Progress Indicators */}
                <div className="flex gap-1.5 md:gap-2 mt-6 md:mt-8">
                    {cards.map((_, idx) => (
                        <div
                            key={idx}
                            className={`h-1.5 rounded-full transition-all duration-300 ${idx === currentIndex ? 'w-6 md:w-8 bg-primary' : 'w-1.5 bg-white/10'}`}
                        />
                    ))}
                </div>

                {/* Controls */}
                <div className="flex items-center gap-4 md:gap-6 mt-8 md:mt-10">
                    <button
                        onClick={(e) => { e.stopPropagation(); handlePrev(); }}
                        disabled={currentIndex === 0}
                        className="h-12 w-12 md:h-14 md:w-14 rounded-full bg-white/5 border border-white/10 flex items-center justify-center disabled:opacity-20 hover:bg-white/10 transition-all active:scale-90"
                    >
                        <span className="text-lg md:text-xl text-white">←</span>
                    </button>

                    <button
                        onClick={() => setIsFlipped(!isFlipped)}
                        className="px-6 md:px-10 py-3 md:py-4 bg-white text-black font-black uppercase tracking-widest text-xs md:text-sm rounded-full hover:scale-105 active:scale-95 transition-all shadow-xl"
                    >
                        Flip Card
                    </button>

                    <button
                        onClick={(e) => { e.stopPropagation(); handleNext(); }}
                        disabled={currentIndex === cards.length - 1}
                        className="h-12 w-12 md:h-14 md:w-14 rounded-full bg-white/5 border border-white/10 flex items-center justify-center disabled:opacity-20 hover:bg-white/10 transition-all active:scale-90"
                    >
                        <span className="text-lg md:text-xl text-white">→</span>
                    </button>
                </div>
            </div>

            <style jsx global>{`
                .perspective-1000 {
                    perspective: 1000px;
                }
                .preserve-3d {
                    transform-style: preserve-3d;
                }
                .backface-hidden {
                    backface-visibility: hidden;
                }
                .rotate-y-180 {
                    transform: rotateY(180deg);
                }
            `}</style>
        </motion.div>,
        document.body
    );
}
