"use client";

import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';

interface QuizQuestion {
    id: string;
    question: string;
    options: string[];
    correct_answer: string;
    explanation?: string;
}

interface Quiz {
    id: string;
    title: string;
    questions: QuizQuestion[];
}

interface QuizViewProps {
    quiz: Quiz;
    onClose: () => void;
}

export default function QuizView({ quiz, onClose }: QuizViewProps) {
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [selectedOption, setSelectedOption] = useState<string | null>(null);
    const [showExplanation, setShowExplanation] = useState(false);
    const [score, setScore] = useState(0);
    const [isFinished, setIsFinished] = useState(false);

    const currentQuestion = quiz.questions[currentQuestionIndex];

    const handleOptionSelect = (option: string) => {
        if (selectedOption !== null) return;
        setSelectedOption(option);
        if (option === currentQuestion.correct_answer) {
            setScore(prev => prev + 1);
        }
        setShowExplanation(true);
    };

    const handleNext = () => {
        if (currentQuestionIndex < quiz.questions.length - 1) {
            setCurrentQuestionIndex(prev => prev + 1);
            setSelectedOption(null);
            setShowExplanation(false);
        } else {
            setIsFinished(true);
        }
    };

    const downloadQuiz = async () => {
        const html2pdf = (await import('html2pdf.js')).default;
        const total = quiz.questions.length;
        const pct = total > 0 ? Math.round((score / total) * 100) : 0;
        const gradeColor = pct >= 80 ? '#22c55e' : pct >= 50 ? '#eab308' : '#ef4444';
        let qHtml = '';
        for (let i = 0; i < quiz.questions.length; i++) {
            const q = quiz.questions[i];
            const letter = (idx: number) => String.fromCharCode(65 + idx);
            const opts = q.options.map((o, oi) => {
                const isCorrect = o === q.correct_answer;
                return `<div class="q-opt${isCorrect ? ' correct' : ''}" style="display:flex;align-items:center;gap:12px;padding:12px 16px;border-radius:14px;border:1px solid ${isCorrect ? 'rgba(34,197,94,0.4)' : 'rgba(255,255,255,0.08)'};background:${isCorrect ? 'rgba(34,197,94,0.1)' : 'rgba(255,255,255,0.04)'};${isCorrect ? 'color:#bbf7d0' : ''}"><span style="width:28px;height:28px;border-radius:8px;background:rgba(0,0,0,0.3);display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:800;flex-shrink:0;color:#fff">${letter(oi)}</span><span style="font-size:14px;font-weight:500;flex:1">${o.replace(/</g, '&lt;')}${isCorrect ? ' <span style="color:#22c55e;font-weight:700">✓</span>' : ''}</span></div>`;
            }).join('');
            const exp = (q.explanation || "That is the correct concept according to the study material.").replace(/</g, '&lt;');
            qHtml += `<div style="margin-top:28px;padding:24px;border-radius:20px;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06)"><div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#818cf8;margin-bottom:8px">Question ${i + 1}</div><div style="font-size:18px;font-weight:600;color:#fff;line-height:1.5;margin-bottom:16px">${q.question.replace(/</g, '&lt;')}</div><div style="display:grid;gap:8px">${opts}</div><div style="margin-top:14px;padding:12px 16px;border-radius:12px;background:rgba(129,140,248,0.08);border:1px solid rgba(129,140,248,0.15);font-size:13px;color:rgba(255,255,255,0.75);line-height:1.6">💡 ${exp}</div></div>`;
        }

        const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
*{margin:0;padding:0;box-sizing:border-box}
.header{text-align:center;padding:0 0 32px;border-bottom:1px solid rgba(255,255,255,0.06)}
.header h1{font-size:28px;font-weight:800;background:linear-gradient(135deg,#818cf8,#60a5fa,#22d3ee);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;letter-spacing:-0.02em}
.score-badge{display:inline-flex;align-items:center;gap:10px;margin-top:16px;padding:10px 24px;border-radius:100px;border:2px solid ${gradeColor};color:${gradeColor};font-size:14px;font-weight:800}
.score-bar{width:200px;height:6px;background:rgba(255,255,255,0.06);border-radius:10px;overflow:hidden;margin:12px auto 0}
.score-fill{height:100%;background:${gradeColor};border-radius:10px;width:${pct}%}
.footer{text-align:center;padding:40px 0;color:rgba(255,255,255,0.15);font-size:12px}
</style></head><body>
<div class="header"><h1>${quiz.title}</h1><div class="score-badge">🏆 ${score}/${total} (${pct}%)</div><div class="score-bar"><div class="score-fill"></div></div></div>
${qHtml}
<div class="footer">Generated by StudyFlow AI</div>
</body></html>`;

        const div = document.createElement('div');
        div.style.cssText = 'width:800px;padding:0 24px;background:#020617;color:#f8fafc;font-family:system-ui,-apple-system,sans-serif;position:fixed;left:50%;top:0;transform:translateX(-50%);z-index:-1;pointer-events:none';
        let clean = html.replace(/<!DOCTYPE[^>]*>/i, '').replace(/<\/?html[^>]*>/gi, '').replace(/<\/?head[^>]*>/gi, '').replace(/<\/?body[^>]*>/gi, '').replace(/<meta[^>]*>/gi, '').replace(/<title[^>]*>.*?<\/title>/gi, '');
        div.innerHTML = clean;
        document.body.appendChild(div);
        try {
            await new Promise(r => requestAnimationFrame(r));
            await html2pdf().set({
                margin: 10,
                filename: `quiz_${new Date().toISOString().slice(0, 10)}.pdf`,
                image: { type: 'jpeg', quality: 0.95 },
                html2canvas: { scale: 2, useCORS: true, backgroundColor: '#020617', logging: true, width: div.scrollWidth, height: div.scrollHeight, scrollY: 0, windowHeight: div.scrollHeight },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            }).from(div).save();
        } catch (e) {
            console.error('PDF generation error:', e);
        } finally {
            document.body.removeChild(div);
        }
    };

    if (typeof window === 'undefined') return null;

    return createPortal(
        <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md"
        >
            <div className="glass-dark border border-white/10 w-full max-w-2xl rounded-3xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
                {/* Header */}
                <div className="p-4 md:p-6 border-bottom border-white/5 flex items-center justify-between bg-white/5">
                    <div className="min-w-0 flex-1">
                        <h2 className="text-lg md:text-xl font-bold text-white truncate">{quiz.title}</h2>
                        {!isFinished && (
                            <p className="text-xs text-white/40 font-medium">Question {currentQuestionIndex + 1} of {quiz.questions.length}</p>
                        )}
                    </div>
                    <div className="flex items-center gap-2 shrink-0 ml-3">
                        <button onClick={downloadQuiz} className="h-9 w-9 rounded-full flex items-center justify-center hover:bg-white/10 transition-colors text-white/60 text-sm font-bold" title="Download Quiz">📥</button>
                        <button onClick={onClose} className="h-9 w-9 rounded-full flex items-center justify-center hover:bg-white/10 transition-colors text-white/60">✕</button>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-4 md:p-8">
                    {!isFinished ? (
                        <AnimatePresence mode="wait">
                            <motion.div
                                key={currentQuestionIndex}
                                initial={{ opacity: 0, x: 20 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: -20 }}
                                className="space-y-8"
                            >
                                <h3 className="text-lg md:text-2xl font-semibold text-white leading-tight">
                                    {currentQuestion.question}
                                </h3>

                                <div className="grid gap-2.5 md:gap-3">
                                    {currentQuestion.options.map((option, idx) => {
                                        const isCorrect = option === currentQuestion.correct_answer;
                                        const isSelected = option === selectedOption;

                                        let variantClass = "border-white/10 bg-white/5 hover:bg-white/10";
                                        if (selectedOption) {
                                            if (isCorrect) variantClass = "border-emerald-500/50 bg-emerald-500/20 text-emerald-200";
                                            else if (isSelected) variantClass = "border-rose-500/50 bg-rose-500/20 text-rose-200";
                                            else variantClass = "opacity-40 border-white/5 bg-transparent";
                                        }

                                        return (
                                            <button
                                                key={idx}
                                                disabled={selectedOption !== null}
                                                onClick={() => handleOptionSelect(option)}
                                                className={`p-3 md:p-4 rounded-2xl border text-left transition-all duration-300 flex items-center gap-3 md:gap-4 min-h-[52px] ${variantClass}`}
                                            >
                                                <span className="h-8 w-8 rounded-lg bg-black/20 flex items-center justify-center font-bold text-sm shrink-0">
                                                    {String.fromCharCode(65 + idx)}
                                                </span>
                                                <span className="font-medium text-sm md:text-base">{option}</span>
                                            </button>
                                        );
                                    })}
                                </div>

                                {showExplanation && (
                                    <motion.div
                                        initial={{ opacity: 0, y: 10 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        className="p-4 rounded-2xl bg-primary/10 border border-primary/20"
                                    >
                                        <p className="text-sm text-primary-light font-bold mb-1 italic">💡 Explanation</p>
                                        <p className="text-sm text-white/70 leading-relaxed">
                                            {currentQuestion.explanation || "That is the correct concept according to the study material."}
                                        </p>
                                    </motion.div>
                                )}
                            </motion.div>
                        </AnimatePresence>
                    ) : (
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="text-center py-12 space-y-6"
                        >
                            <div className="h-24 w-24 rounded-full bg-gradient-study mx-auto flex items-center justify-center shadow-lg shadow-primary/20">
                                <span className="text-4xl">🏆</span>
                            </div>
                            <div>
                                <h3 className="text-3xl font-black text-white">Quiz Complete!</h3>
                                <p className="text-white/60 mt-2">Final Score: {score} / {quiz.questions.length}</p>
                            </div>

                            <div className="w-full max-w-xs mx-auto bg-white/5 rounded-2xl p-4 border border-white/10">
                                <span className="text-xs uppercase tracking-widest font-black text-white/30">Mastery Rating</span>
                                <div className="h-3 w-full bg-black/40 rounded-full mt-3 overflow-hidden">
                                    <motion.div
                                        initial={{ width: 0 }}
                                        animate={{ width: `${(score / quiz.questions.length) * 100}%` }}
                                        className="h-full bg-gradient-to-r from-primary to-accent"
                                    />
                                </div>
                            </div>

                            <button
                                onClick={onClose}
                                className="px-8 py-3 bg-primary hover:bg-primary-dark text-white rounded-full font-bold shadow-lg shadow-primary/20 transition-all hover:scale-105"
                            >
                                Continue Studying
                            </button>
                        </motion.div>
                    )}
                </div>

                {!isFinished && selectedOption && (
                    <div className="p-4 md:p-6 border-t border-white/5 bg-white/5">
                        <button
                            onClick={handleNext}
                            className="w-full py-3.5 md:py-4 bg-primary hover:bg-primary-dark text-white rounded-2xl font-bold shadow-lg shadow-primary/10 transition-all active:scale-[0.98]"
                        >
                            {currentQuestionIndex < quiz.questions.length - 1 ? "Next Question" : "See Results"}
                        </button>
                    </div>
                )}
            </div>
        </motion.div>,
        document.body
    );
}
